"""Router-side constants."""
BUFFER_SIZE = 4096
ENCODING = "utf-8"

MSG_REGISTER = "REGISTER_ROUTER"
MSG_TOPOLOGY = "TOPOLOGY_UPDATE"
MSG_ROUTING_TABLE = "ROUTING_TABLE"
MSG_LINK_COST = "LINK_COST_UPDATE"
MSG_ACK = "ACK"
MSG_ERROR = "ERROR"
